Fix error: unexpected character after line continuation char
This fixes the following error thrown by Python when I executed the script:
   SyntaxError: unexpected character after line continuation character

The code had two lines where the \ (line continuation character) was followed by other text, which is not allowed. Removing the \ fixed the error messages.